package httpapi

import "net/http"

func (s *server) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) { reply(w, 200, map[string]string{"status": "ok"}) })
	mux.HandleFunc("POST /auth/register", s.register)
	mux.HandleFunc("POST /auth/login", s.login)
	mux.HandleFunc("POST /auth/google", s.googleLogin)
	mux.HandleFunc("GET /auth/me", s.me)
	mux.HandleFunc("GET /events", s.listEvents)
	mux.HandleFunc("GET /templates", s.listTemplates)
	mux.HandleFunc("POST /events", s.createEvent)
	mux.HandleFunc("PATCH /events/{id}", s.updateEvent)
	mux.HandleFunc("PATCH /events/{id}/design", s.updateDesign)
	mux.HandleFunc("POST /maps/resolve", s.resolveMapsURL)
	mux.HandleFunc("GET /events/{id}/guests", s.listGuests)
	mux.HandleFunc("GET /events/{id}/seating", s.getSeating)
	mux.HandleFunc("PATCH /events/{id}/seating", s.saveSeating)
	mux.HandleFunc("POST /events/{id}/guests", s.addGuest)
	mux.HandleFunc("POST /events/{id}/guests/import", s.importGuests)
	mux.HandleFunc("POST /events/{id}/photos", s.uploadPhoto)
	mux.HandleFunc("GET /events/{id}/photos/{key}", s.ownerPhoto)
	mux.HandleFunc("POST /events/{id}/send-invitations", s.sendInvitations)
	mux.HandleFunc("POST /events/{id}/couple-invitations", s.inviteCouple)
	mux.HandleFunc("POST /events/{id}/couple-accounts", s.createCoupleAccount)
	mux.HandleFunc("GET /couple-invites/{token}", s.coupleInviteDetails)
	mux.HandleFunc("POST /couple-invites/{token}/accept", s.acceptCouple)
	mux.HandleFunc("GET /public/events/{kind}/{slug}", s.publicEvent)
	mux.HandleFunc("GET /public/events/{kind}/{slug}/photos/{key}", s.publicPhoto)
	mux.HandleFunc("POST /public/rsvp/{token}", s.rsvp)
	mux.HandleFunc("GET /public/rsvp/{token}", s.rsvpDetails)
	mux.HandleFunc("POST /events/{id}/checkout", s.checkout)
	mux.HandleFunc("POST /events/{id}/publish", s.publish)
	mux.HandleFunc("GET /events/{id}/deployment", s.deploymentStatus)
	mux.HandleFunc("POST /webhooks/stripe", s.stripeWebhook)
	mux.HandleFunc("POST /webhooks/wazend", s.wazendWebhook)
	return cors(s.rateLimit(mux))
}
